// Generated by Wrangler on Sun Sep 15 2024 12:44:36 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	BUCKET_DOMAIN: "example.com";
	BUCKET: R2Bucket;
	AI: Ai;
}
