#:schema node_modules/wrangler/config-schema.json
name = "demo-app"
compatibility_date = "2024-08-15"
pages_build_output_dir = "./build/client"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV"
id = "d3ea0404d06e4a3faf801adfa28dd9fe"
preview_id = "33b04eede7b04caf81257b09f3bbf53a"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "my-bucket"
preview_bucket_name = "my-bucket"
