#:schema node_modules/wrangler/config-schema.json
name = "demo-app"
compatibility_date = "2024-08-15"
pages_build_output_dir = "./build/client"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV"
id = "48ce791d165a4a04ba04b5641556b4b7"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "dc-react-summit-nov-2024-demo"
